// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_config/flutter_config.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: FlutterConfig.get('WEB_API_KEY'),
    appId: FlutterConfig.get('WEB_APP_ID'),
    messagingSenderId: FlutterConfig.get('MESSAGING_SENDERING_ID'),
    projectId: FlutterConfig.get('PROJECT_ID'),
    authDomain: FlutterConfig.get('WEB_AUTH_DOMAIN'),
    storageBucket: FlutterConfig.get('STORAGE_BUCKET'),
    measurementId: FlutterConfig.get('WEB_MEASUREMENT_ID'),
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: FlutterConfig.get('ANDROID_API_KEY'),
    appId: FlutterConfig.get('ANDROID_APP_ID'),
    messagingSenderId: FlutterConfig.get('MESSAGING_SENDERING_ID'),
    projectId: FlutterConfig.get('PROJECT_ID'),
    storageBucket: FlutterConfig.get('STORAGE_BUCKET'),
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: FlutterConfig.get('IOS_API_KEY'),
    appId: FlutterConfig.get('IOS_APP_ID'),
    messagingSenderId: FlutterConfig.get('MESSAGING_SENDERING_ID'),
    projectId: FlutterConfig.get('PROJECT_ID'),
    storageBucket: FlutterConfig.get('STORAGE_BUCKET'),
    iosBundleId: FlutterConfig.get('IOS_BUNDLE_ID'),
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: FlutterConfig.get('MACOS_API_KEY'),
    appId: FlutterConfig.get('MACOS_APP_ID'),
    messagingSenderId: FlutterConfig.get('MESSAGING_SENDERING_ID'),
    projectId: FlutterConfig.get('PROJECT_ID'),
    storageBucket: FlutterConfig.get('STORAGE_BUCKET'),
    iosBundleId: FlutterConfig.get('MACOS_IOS_BUNDLE_ID'),
  );
}
