// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoeqn4EVI_cia1L6vDRSJhInRBqJlC2Ds',
    appId: '1:257558588020:web:1719ee878db8c508197f21',
    messagingSenderId: '257558588020',
    projectId: 'knu-capstone-diet-app',
    authDomain: 'knu-capstone-diet-app.firebaseapp.com',
    storageBucket: 'knu-capstone-diet-app.appspot.com',
    measurementId: 'G-R7V8RE5014',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALRN9elCuGqXk5PXWkBAQQTEYAk6I3n0A',
    appId: '1:257558588020:android:99f577d6bf7400ce197f21',
    messagingSenderId: '257558588020',
    projectId: 'knu-capstone-diet-app',
    storageBucket: 'knu-capstone-diet-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmKrMhzJUiXqkTxG2DIYXbzYWCIiAvIrA',
    appId: '1:257558588020:ios:72bd56a7e9e4758d197f21',
    messagingSenderId: '257558588020',
    projectId: 'knu-capstone-diet-app',
    storageBucket: 'knu-capstone-diet-app.appspot.com',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmKrMhzJUiXqkTxG2DIYXbzYWCIiAvIrA',
    appId: '1:257558588020:ios:af7a14eaafdb707d197f21',
    messagingSenderId: '257558588020',
    projectId: 'knu-capstone-diet-app',
    storageBucket: 'knu-capstone-diet-app.appspot.com',
    iosBundleId: 'com.example.project1.RunnerTests',
  );
}
